spring:
  application:
    name: finance-eureka-discovery
  main:
    banner-mode: OFF

server:
  port: 8761

eureka:
  instance:
    hostname: finance-eureka-discovery
  client:
    registerWithEureka: false
    fetchRegistry: false

logging:
  level:
    ROOT: INFO
    com.netflix.eureka: 'OFF'
  file:
    max-history: 0
    max-size: 1GB
default:
  locale: en_US
