version: "3.8"
services:
   finance-core:
      image: finance-core
      build: ./finance-core
      container_name: finance-core
      ports:
         - "1905:1905"
      depends_on:
         - finance-eureka-discovery
         - mongo
         - mongo-express
      deploy:
         replicas: 2

   finance-eureka-discovery:
      image: finance-eureka-discovery
      build: ./finance-eureka-discovery
      container_name: finance-eureka-discovery
      restart: always
      ports:
         - "8761:8761"
      deploy:
         replicas: 1

   mongo:
      image: mongo:4.4.0
      container_name: mongo
      restart: always
      ports:
         - "27017:27017"
      environment:
         MONGO_INITDB_ROOT_USERNAME: root
         MONGO_INITDB_ROOT_PASSWORD: example
      deploy:
         replicas: 1

   mongo-express:
      image: mongo-express:0.54.0
      container_name: mongo-express
      restart: always
      ports:
         - "8081:8081"
      environment:
         ME_CONFIG_MONGODB_ADMINUSERNAME: root
         ME_CONFIG_MONGODB_ADMINPASSWORD: example
      deploy:
         replicas: 1
